// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cifhqexowuzfacwndvut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZmhxZXhvd3V6ZmFjd25kdnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTE1OTYsImV4cCI6MjA1NzcyNzU5Nn0.SnYqkOFNA6qWv9twH2hMJFXjhabCW5L0OUbKcpxWK1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);