
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cifhqexowuzfacwndvut.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNpZmhxZXhvd3V6ZmFjd25kdnV0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNTE1OTYsImV4cCI6MjA1NzcyNzU5Nn0.SnYqkOFNA6qWv9twH2hMJFXjhabCW5L0OUbKcpxWK1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Get the current app URL from window location for redirects
const getAppUrl = () => {
  // In browser environment, use the current window location
  if (typeof window !== 'undefined') {
    const protocol = window.location.protocol;
    const host = window.location.host;
    return `${protocol}//${host}`;
  }
  // Fallback for non-browser environments
  return 'http://localhost:8080';
};

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      // Use the current app URL dynamically for redirects
      redirectTo: `${getAppUrl()}/auth/callback`,
    },
  }
);
